### ISSUE TITLE
Bean Writer Restrictive Functionality

### ISSUE THREAD

**Issue by vivekdhiman** [onehippo/essentials#9]
Hi, 

Bean writer is a great tool in reducing development efforts, but its does't have functionality to map specific bean to specific package, rather it created all beans in one package , provided in configuration file. Such type of use-case are least helpful in projects. Can it be enhanced to provide two text fields 

1) Enter DocumentType/CompoundType
2) Enter Package Name

Generate Bean

Thanks,

**Comment by jeroenhoffman** [comment]
Hi Vivek,
Thanks for your feedback, that is always welcome. It will have better visibility though if you create an improvement ticket it in our JIRA system at https://issues.onehippo.com/projects/ESSENTIALS.

Also, the code base at this location is rather outdated, we moved to https://code.onehippo.org/cms-community/hippo-essentials 

Hope this helps,
Jeroen Hoffman

**Comment by vivekdhiman** [comment]
@jeroenhoffman Thanks, let me close this issue and will create separate jira ticket
